### ISSUE TITLE
Conflict of versions for selenium-java in the POM of io.github.bonigarcia:selenium-jupiter:2.1.1

### ISSUE THREAD

**Issue by vmassol** [bonigarcia/selenium-jupiter#11]
```
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for org.seleniumhq.selenium:selenium-java:2.44.0 paths to dependency are:
+-org.xwiki.platform:xwiki-platform-test-docker:10.6-SNAPSHOT
  +-io.github.bonigarcia:selenium-jupiter:2.1.1
    +-org.seleniumhq.selenium:selenium-java:2.44.0 (managed) <-- org.seleniumhq.selenium:selenium-java:3.11.0
and
+-org.xwiki.platform:xwiki-platform-test-docker:10.6-SNAPSHOT
  +-org.seleniumhq.selenium:selenium-server:3.11.0
    +-org.seleniumhq.selenium:selenium-java:2.44.0 (managed) <-- org.seleniumhq.selenium:selenium-java:3.11.0
and
+-org.xwiki.platform:xwiki-platform-test-docker:10.6-SNAPSHOT
  +-io.github.bonigarcia:selenium-jupiter:2.1.1
    +-io.appium:java-client:5.0.4
      +-org.seleniumhq.selenium:selenium-java:2.44.0 (managed) <-- org.seleniumhq.selenium:selenium-java:3.6.0
```

So the reason is that the version of io.appium:java-client used (5.0.4) depends on selenium-java 2.44.0 instead of 3.11.0. Best would be to either upgrade the dependency to a more recent version or use an `<exclusion>` in the java-client dependency.

FTM I'll do the exclusion on XWiki's side. Thanks

**Comment by bonigarcia** [comment]
I've been trying to solve these warnings using the `dependencyConvergence` rule of the plugin `maven-enforcer-plugin` but I didn't succeed. There are several second level transitive dependencies which are causing these type problems and it is not trivial to solve, since exclusions might lead to class not found exceptions in runtime. Besides, in development, `maven-enforcer-plugin` also analyses test dependencies, and the list of this kind of warnings is huge. Finally, the dependencies versions in this project are constantly evolving, and I suspect that maintaining a coherent exclusion configuration in the future will be very costly.

All in all, I decided not investing more effort in trying to solve this. For the best of my knowledge these are warnings which are not impacting the correct performance of Selenium-Jupiter.

**Comment by vmassol** [comment]
> I've been trying to solve these warnings

Thanks for trying! :)

> For the best of my knowledge these are warnings which are not impacting the correct performance of Selenium-Jupiter.

They just mean that you cannot really know which version is going to be resolved (it'll depend on the order of your deps since Maven resolves from closest to your top level pom). We had the issue in XWiki land and decided to use the enforcer plugin so that it doesn't happen again.
