### ISSUE TITLE
64-bit Internet Explorer is being opened even if it is set to be 32-bit

### ISSUE THREAD

**Issue by vicajoy** [bonigarcia/selenium-jupiter#122]
**Description of the problem**: 

Used the following test:

    @TestMethodOrder(MethodOrderer.OrderAnnotation.class)
    @SingleSession
    @ExtendWith(SeleniumExtension.class)

    public class FailureCreatesScreenshotTest {

        private WebDriver driver;

        FailureCreatesScreenshotTest(WebDriver driver) {
            this.driver = driver;
        }

        @BeforeAll
        public static void setup() {
            WebDriverManager.iedriver().arch32().setup();
        }    

        @Test
        @Order(1)
        void testStep1() {
            step1(driver);
        }

        @Test
        @Order(2)
        void testStep2() {
            step2(driver);
        }

        private void step1(WebDriver driver) {
            driver.get("https://bonigarcia.github.io/selenium-jupiter/");
            assertTrue(driver.getTitle().contains("JUnit 5 extension for Selenium"));
        }

        private void step2(WebDriver driver) {
            WebElement about = driver.findElement(By.linkText("About"));
            about.click();
            assertFalse(about.isDisplayed());
        }

The 64-bit Internet Explorer is being opened despite the fact that I use `WebDriverManager.iedriver().arch32().setup();` to setup the 32-bit IE.

Please note that it works as expected on the `selenium-jupiter-3.3.4` version.

**Browser and version**: Internet Explorer 11

**Operating system**: Windows 10

**Selenium-Jupiter version**: 3.3.5 and above

**Comment by bonigarcia** [comment]
I am developing a new major release of Selenium-Jupiter currently. This new version is going to change many things. I will try to implement a test to check this behavior in the new release.

**Comment by bonigarcia** [comment]
I don't know what could be problem here, since the line `WebDriverManager.iedriver().arch32().setup();` should affect to the driver (for IE in this case), but not the browser.

In any case, things are going to be quite different in next release (Selenium-Jupiter 4), which I am developing these days. For instance, to specify a custom instance of WebDriverManager, it can be done like [this](https://github.com/bonigarcia/selenium-jupiter/blob/master/src/test/java/io/github/bonigarcia/seljup/test/advance/CustomConfigWdmJupiterTest.java).

Please stay tuned for the next version.
